export * from "@/pages/dashboard/home";
export * from "@/pages/dashboard/profile";
export * from "@/pages/dashboard/tables";
export * from "@/pages/dashboard/notifications";
export * from "@/pages/dashboard/complain";
export * from "@/pages/dashboard/complainList";
export * from "@/pages/dashboard/categories";
export * from "@/pages/dashboard/welcome";
export * from "@/pages/dashboard/employee";
